[build]
  publish = "."

[[headers]]
  for = "/content/*"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"

[[headers]]
  for = "/admin/*"
  [headers.values]
    X-Robots-Tag = "noindex"
